/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login by phone + password (DRF SimpleJWT) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange refresh for a new access token (refresh is NOT rotated) */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/logged-in/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["loggedIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-app/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Place typeahead (Google Places proxied) */
        get: operations["searchPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Business detail by id or Google place_id (get-or-create) */
        get: operations["getBusiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/search/{viewer}/{query}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Member search by name/username */
        get: operations["searchMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/following/{userId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People the user follows */
        get: operations["getFollowing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/followers/{userId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Followers of the user */
        get: operations["getFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scores/{userId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Network scores visible to the authenticated user. Returns a large list of
         *     {user_id, business_id, value, category, …} across followed users.
         *     Query params do NOT filter server-side — client-filter by business_id.
         *     Cache aggressively; easy to 429 if polled per place.
         */
        get: operations["getNetworkScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recs/{userId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personalized recommendation percentiles by business_id */
        get: operations["getRecs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get-ranking/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A user's ranked Been list for a category (ignores business query filters) */
        get: operations["getRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get-bookmark/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A user's Want to Try bookmarks */
        get: operations["getBookmark"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-business-photo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a user's photos for a business */
        get: operations["listPhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-business-photo/{photoId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photo (or cover) object by id */
        get: operations["getPhoto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        IntId: number;
        /** @description Google Places place_id (e.g. ChIJ…) */
        PlaceId: string;
        /**
         * @description List/category codes. RES default; BAK observed on bakery scores.
         * @enum {string}
         */
        Category: "RES" | "BAR" | "COFFEE" | "BAKERY" | "DESSERT" | "OTHER" | "BAK";
        LoginRequest: {
            /**
             * @description E.164 phone, e.g. +15551234567
             * @example +15551234567
             */
            phone_no: string;
            password: string;
        };
        TokenPair: {
            access: string;
            refresh: string;
        };
        RefreshRequest: {
            refresh: string;
        };
        RefreshResponse: {
            access: string;
        };
        LoggedInUser: {
            id: components["schemas"]["Uuid"];
            username: string;
            full_name?: string;
            first_name?: string;
            last_name?: string;
            phone_no?: string;
            email?: string | null;
            home_city?: string | null;
            profile_photo?: string | null;
        } & {
            [key: string]: unknown;
        };
        LoggedInResponse: {
            results: components["schemas"]["LoggedInUser"][];
        };
        Business: {
            id: components["schemas"]["IntId"];
            place_id?: string | null;
            name: string;
            status?: string;
            city?: string | null;
            borough?: string | null;
            neighborhood?: string | null;
            country?: string | null;
            lat?: number | null;
            lng?: number | null;
            price?: number | null;
            price_key?: string | null;
            website?: string | null;
            phone_number?: string | null;
            cuisines?: string[];
            quick_link?: string | null;
            tz?: string | null;
            default_category?: string;
        } & {
            [key: string]: unknown;
        };
        BusinessResponse: {
            results: components["schemas"]["Business"][];
        } | components["schemas"]["Business"];
        SearchPrediction: {
            place_id: components["schemas"]["PlaceId"];
            business?: number | null;
            structured_formatting?: {
                main_text?: string;
                secondary_text?: string;
            };
            types?: string[];
            distance_meters?: number | null;
            default_category?: string | null;
        } & {
            [key: string]: unknown;
        };
        SearchResponse: {
            predictions: components["schemas"]["SearchPrediction"][];
        };
        MemberSummary: {
            id: components["schemas"]["Uuid"];
            username: string;
            full_name?: string | null;
            first_name?: string;
            last_name?: string;
            instagram_url?: string | null;
            tiktok_url?: string | null;
            profile_photo?: string | null;
            photo?: string | null;
            public?: boolean;
            company?: string | null;
            school?: string | null;
            /** Format: date-time */
            created_dt?: string;
        } & {
            [key: string]: unknown;
        };
        MemberListResponse: {
            results: components["schemas"]["MemberSummary"][];
        };
        NetworkScore: {
            user_id: components["schemas"]["Uuid"];
            business_id: components["schemas"]["IntId"];
            /** @description Beli 0–10 style score */
            value: number;
            category: string;
            num_visits?: number;
            labels?: string[];
        } & {
            [key: string]: unknown;
        };
        NetworkScoreList: components["schemas"]["NetworkScore"][];
        RecItem: {
            business_id: components["schemas"]["IntId"];
            expected_percentile: number;
        } & {
            [key: string]: unknown;
        };
        RecList: components["schemas"]["RecItem"][];
        RankingListItem: {
            id: components["schemas"]["IntId"];
            user: components["schemas"]["Uuid"];
            business: components["schemas"]["Business"];
            score?: number | null;
            value?: number | null;
            category?: string;
            visit_dates?: string[];
            /** Format: date-time */
            created_dt?: string;
        } & {
            [key: string]: unknown;
        };
        RankingListResponse: {
            results: components["schemas"]["RankingListItem"][];
        };
        BookmarkListItem: {
            id: components["schemas"]["IntId"];
            user: components["schemas"]["Uuid"];
            business: components["schemas"]["Business"];
        } & {
            [key: string]: unknown;
        };
        /** @description Category-keyed map, e.g. { "Restaurants": [...] } */
        BookmarkListResponse: {
            [key: string]: components["schemas"]["BookmarkListItem"][];
        };
        PhotoRecord: {
            id?: components["schemas"]["IntId"];
            user?: components["schemas"]["Uuid"] | string;
            business?: components["schemas"]["IntId"] | string;
            image?: string | null;
            thumbnail?: string | null;
            bb_image?: string | null;
            description?: string | null;
            status?: string;
        } & {
            [key: string]: unknown;
        };
        PhotoListResponse: {
            results: components["schemas"]["PhotoRecord"][] | components["schemas"]["PhotoRecord"];
        };
        ErrorDetail: {
            detail?: string;
            code?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Beli user UUID */
        UserIdPath: components["schemas"]["Uuid"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Access + refresh tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Refresh invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    loggedIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged-in user envelope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedInResponse"];
                };
            };
        };
    };
    searchPlaces: {
        parameters: {
            query: {
                term: string;
                city?: string;
                coords?: string;
                user: components["schemas"]["Uuid"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Predictions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    getBusiness: {
        parameters: {
            query?: {
                id?: number;
                place_id?: components["schemas"]["PlaceId"];
                from_business_page?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Business or results wrapper */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessResponse"];
                };
            };
            /** @description No identifier */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchMembers: {
        parameters: {
            query?: {
                page?: number;
                include_followed?: string;
            };
            header?: never;
            path: {
                viewer: components["schemas"]["Uuid"];
                query: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member matches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponse"];
                };
            };
        };
    };
    getFollowing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Beli user UUID */
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Following list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponse"];
                };
            };
        };
    };
    getFollowers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Beli user UUID */
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Followers list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponse"];
                };
            };
        };
    };
    getNetworkScores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Beli user UUID */
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flat score list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkScoreList"];
                };
            };
            /** @description Throttled */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRecs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Beli user UUID */
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rec list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecList"];
                };
            };
        };
    };
    getRanking: {
        parameters: {
            query: {
                user: components["schemas"]["Uuid"];
                category?: components["schemas"]["Category"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Been list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingListResponse"];
                };
            };
            /** @description Missing user identifier */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBookmark: {
        parameters: {
            query: {
                user: components["schemas"]["Uuid"];
                category?: components["schemas"]["Category"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category-keyed bookmarks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkListResponse"];
                };
            };
        };
    };
    listPhotos: {
        parameters: {
            query?: {
                user?: components["schemas"]["Uuid"];
                business?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Photo list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoListResponse"];
                };
            };
        };
    };
    getPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Photo record envelope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoListResponse"];
                };
            };
        };
    };
}
